package com.hyunseo.hyunseorpg.shop;

public enum ShopTransactionReason {
    SUCCESS,
    PURCHASE_DISABLED,
    FARMING_PROFILE_NOT_READY,
    FARMING_CROP_LOCKED,
    SALE_DISABLED,
    INVALID_PRICE,
    INSUFFICIENT_COINS,
    INVENTORY_FULL,
    NO_MATCHING_ITEMS,
    PRICE_OVERFLOW,
    TRANSACTION_FAILED
}
