package com.hyunseo.hyunseorpg.alchemy;

public enum EffectSourceType {
    POTION_DRINK, POTION_SPLASH, POTION_LINGERING, POTION_FIREBALL, EQUIPMENT, ENCHANTMENT,
    MONSTER_SKILL, BOSS_SKILL, ENVIRONMENT, COMMAND, OTHER
}
